"use client";
import React from "react";

// Tiny focused markdown renderer for the Rule Check audit drawer's User
// Prompt and System Prompt tabs. The prompts we render are generated by
// lib/rule-check/prompt.ts so we know the syntax surface up-front:
//   - `# / ## / ### / ####` headings
//   - fenced ``` code blocks (```json … ```)
//   - inline `code` and **bold**
//   - blockquotes (lines starting with `> `)
//   - bullet (- foo) and ordered (1. foo) lists
//   - hard paragraph breaks on blank lines
//
// We deliberately do NOT support tables / images / links / nested lists.
// Adding remark+react-markdown would be ~80kb of dependency for a feature
// that fits in this file.

type Inline = { type: "text"; value: string } | { type: "code"; value: string } | { type: "bold"; children: Inline[] };

function parseInline(line: string): Inline[] {
  const out: Inline[] = [];
  let i = 0;
  while (i < line.length) {
    // inline code: `…`
    if (line[i] === "`") {
      const close = line.indexOf("`", i + 1);
      if (close !== -1) {
        out.push({ type: "code", value: line.slice(i + 1, close) });
        i = close + 1;
        continue;
      }
    }
    // bold: **…**
    if (line[i] === "*" && line[i + 1] === "*") {
      const close = line.indexOf("**", i + 2);
      if (close !== -1) {
        out.push({ type: "bold", children: parseInline(line.slice(i + 2, close)) });
        i = close + 2;
        continue;
      }
    }
    // plain run — gather chars until the next special start
    let j = i;
    while (j < line.length && line[j] !== "`" && !(line[j] === "*" && line[j + 1] === "*")) j++;
    out.push({ type: "text", value: line.slice(i, j) });
    i = j;
  }
  return out;
}

function renderInline(inlines: Inline[], keyPrefix: string): React.ReactNode {
  return inlines.map((node, idx) => {
    const k = `${keyPrefix}.${idx}`;
    if (node.type === "text") return <React.Fragment key={k}>{node.value}</React.Fragment>;
    if (node.type === "code") {
      return (
        <code
          key={k}
          className="mono"
          style={{
            background: "var(--c-panel)",
            border: "1px solid var(--c-line)",
            borderRadius: 3,
            padding: "0 4px",
            fontSize: "0.92em",
          }}
        >
          {node.value}
        </code>
      );
    }
    return (
      <strong key={k} style={{ fontWeight: 600 }}>
        {renderInline(node.children, k)}
      </strong>
    );
  });
}

type Block =
  | { kind: "heading"; level: 1 | 2 | 3 | 4; text: string }
  | { kind: "code"; lang: string; text: string }
  | { kind: "quote"; lines: string[] }
  | { kind: "ulist"; items: string[] }
  | { kind: "olist"; items: string[] }
  | { kind: "para"; lines: string[] }
  | { kind: "blank" };

function parseBlocks(src: string): Block[] {
  const lines = src.split("\n");
  const blocks: Block[] = [];
  let i = 0;
  while (i < lines.length) {
    const line = lines[i];

    // code fence
    const fence = line.match(/^```(\w*)\s*$/);
    if (fence) {
      const lang = fence[1] ?? "";
      i += 1;
      const buf: string[] = [];
      while (i < lines.length && !/^```\s*$/.test(lines[i])) {
        buf.push(lines[i]);
        i += 1;
      }
      // consume closing fence (if present)
      if (i < lines.length) i += 1;
      blocks.push({ kind: "code", lang, text: buf.join("\n") });
      continue;
    }

    // heading
    const h = line.match(/^(#{1,4})\s+(.*)$/);
    if (h) {
      blocks.push({ kind: "heading", level: h[1].length as 1 | 2 | 3 | 4, text: h[2] });
      i += 1;
      continue;
    }

    // blockquote group
    if (/^>\s?/.test(line)) {
      const qbuf: string[] = [];
      while (i < lines.length && /^>\s?/.test(lines[i])) {
        qbuf.push(lines[i].replace(/^>\s?/, ""));
        i += 1;
      }
      blocks.push({ kind: "quote", lines: qbuf });
      continue;
    }

    // unordered list
    if (/^[-*]\s+/.test(line)) {
      const items: string[] = [];
      while (i < lines.length && /^[-*]\s+/.test(lines[i])) {
        items.push(lines[i].replace(/^[-*]\s+/, ""));
        i += 1;
      }
      blocks.push({ kind: "ulist", items });
      continue;
    }

    // ordered list
    if (/^\d+\.\s+/.test(line)) {
      const items: string[] = [];
      while (i < lines.length && /^\d+\.\s+/.test(lines[i])) {
        items.push(lines[i].replace(/^\d+\.\s+/, ""));
        i += 1;
      }
      blocks.push({ kind: "olist", items });
      continue;
    }

    // blank
    if (line.trim() === "") {
      blocks.push({ kind: "blank" });
      i += 1;
      continue;
    }

    // paragraph — gather adjacent non-blank, non-special lines
    const pbuf: string[] = [];
    while (
      i < lines.length &&
      lines[i].trim() !== "" &&
      !/^```/.test(lines[i]) &&
      !/^(#{1,4})\s+/.test(lines[i]) &&
      !/^>\s?/.test(lines[i]) &&
      !/^[-*]\s+/.test(lines[i]) &&
      !/^\d+\.\s+/.test(lines[i])
    ) {
      pbuf.push(lines[i]);
      i += 1;
    }
    blocks.push({ kind: "para", lines: pbuf });
  }
  return blocks;
}

export function MiniMarkdown({ source }: { source: string }) {
  const blocks = React.useMemo(() => parseBlocks(source), [source]);
  return (
    <div className="text-ink-1" style={{ fontSize: 13, lineHeight: 1.55 }}>
      {blocks.map((b, idx) => {
        const k = `b${idx}`;
        if (b.kind === "blank") return null;
        if (b.kind === "heading") {
          const sizes = { 1: 19, 2: 16.5, 3: 14.5, 4: 13.5 } as const;
          const weights = { 1: 600, 2: 600, 3: 600, 4: 500 } as const;
          const marginTop = b.level === 1 ? 0 : b.level === 2 ? 18 : 12;
          return (
            <div
              key={k}
              className="text-ink-1"
              style={{
                fontSize: sizes[b.level],
                fontWeight: weights[b.level],
                marginTop,
                marginBottom: 6,
                letterSpacing: "-0.005em",
              }}
            >
              {renderInline(parseInline(b.text), k)}
            </div>
          );
        }
        if (b.kind === "code") {
          return (
            <pre
              key={k}
              className="mono"
              style={{
                background: "var(--c-panel)",
                border: "1px solid var(--c-line)",
                borderRadius: 4,
                padding: "10px 12px",
                fontSize: 11.5,
                lineHeight: 1.5,
                overflowX: "auto",
                whiteSpace: "pre",
                margin: "4px 0 8px",
              }}
            >
              {b.text}
            </pre>
          );
        }
        if (b.kind === "quote") {
          return (
            <blockquote
              key={k}
              style={{
                borderLeft: "3px solid var(--c-accent)",
                background: "color-mix(in oklab, var(--c-accent) 6%, transparent)",
                padding: "8px 12px",
                margin: "6px 0",
                color: "var(--c-ink-1)",
                borderRadius: "0 3px 3px 0",
              }}
            >
              {b.lines.map((l, j) => (
                <div key={`${k}.q${j}`} style={{ marginBottom: j === b.lines.length - 1 ? 0 : 4 }}>
                  {renderInline(parseInline(l), `${k}.q${j}`)}
                </div>
              ))}
            </blockquote>
          );
        }
        if (b.kind === "ulist") {
          return (
            <ul key={k} style={{ margin: "4px 0 8px", paddingLeft: 22, listStyle: "disc" }}>
              {b.items.map((it, j) => (
                <li key={`${k}.li${j}`} style={{ marginBottom: 2 }}>
                  {renderInline(parseInline(it), `${k}.li${j}`)}
                </li>
              ))}
            </ul>
          );
        }
        if (b.kind === "olist") {
          return (
            <ol key={k} style={{ margin: "4px 0 8px", paddingLeft: 22, listStyle: "decimal" }}>
              {b.items.map((it, j) => (
                <li key={`${k}.li${j}`} style={{ marginBottom: 2 }}>
                  {renderInline(parseInline(it), `${k}.li${j}`)}
                </li>
              ))}
            </ol>
          );
        }
        // paragraph
        return (
          <p key={k} style={{ margin: "4px 0 8px" }}>
            {b.lines.map((l, j) => (
              <React.Fragment key={`${k}.p${j}`}>
                {renderInline(parseInline(l), `${k}.p${j}`)}
                {j < b.lines.length - 1 ? <br /> : null}
              </React.Fragment>
            ))}
          </p>
        );
      })}
    </div>
  );
}
