// Deterministic template renderer — AgentSpec → Inngest agent .ts skeleton.
//
// 90% of every real AO agent has the same shape (banner + imports + createFn
// + step.run sequence + emit). The skeleton is therefore boilerplate that
// doesn't need an LLM. LLM Call B (step-body-filler) only fills the body
// of each `step.run` callback.
//
// Plain string templating — no Handlebars, no JSX. Simpler to read, simpler
// to evolve. If templates grow gnarly later we revisit.

import type { AgentSpec, AgentSpecStep } from '../spec-types';
import { findTool } from '../registries/tool-registry.raas';

export type StepBody = {
  /** kebab-case id matching AgentSpec.steps[].id */
  id: string;
  /** Imports the step body needs (deduped at render time). */
  imports?: Array<{ from: string; names: string[] }>;
  /** TS source for the step.run callback body (without outer braces). */
  body: string;
};

export type RenderInput = {
  spec: AgentSpec;
  /** Per-step bodies filled by LLM Call B. If omitted for a step we emit a TODO. */
  stepBodies?: StepBody[];
  /** Generation provenance shown in the banner. Defaults to "now" + "AO codegen". */
  generatedAt?: string;
  generatedBy?: string;
};

export type RenderResult = {
  /** Target path the operator will save this to. */
  suggestedPath: string;
  /** Full file content as TS source. */
  content: string;
};

export function renderAgent({
  spec,
  stepBodies = [],
  generatedAt = new Date().toISOString(),
  generatedBy = 'AO codegen',
}: RenderInput): RenderResult {
  const stepBodyById = new Map(stepBodies.map((s) => [s.id, s]));

  const camelName = kebabToCamel(spec.slug.replace(/-agent$/, '')) + 'Agent';
  const agentIdConst = spec.slug;
  const inboundImports = collectImports(spec, stepBodyById);
  const importBlock = formatImports(inboundImports);

  const stepBlocks = spec.steps
    .map((step) => renderStep(step, stepBodyById.get(step.id)))
    .join('\n\n      ');

  const emitBlock = spec.emitEvents.length
    ? spec.emitEvents
        .map(
          (e) =>
            `await inngest.send({ name: '${e}', data: { /* TODO: populate from upstream step outputs */ } });`,
        )
        .join('\n      ')
    : '// (no emitted events declared)';

  const content = `// ${spec.slug} — ${spec.displayName}
//
// Stage: ${spec.stage}  ·  Owner: ${spec.ownerTeam}
// Trigger: ${spec.triggerEvent}
// Emits:   ${spec.emitEvents.join(', ') || '(none)'}
//
// Generated by ${generatedBy} at ${generatedAt}.
// Do not hand-edit — regenerate from the spec instead.

${importBlock}

const AGENT_ID = '${agentIdConst}';
const AGENT_NAME = '${camelName}';

export const ${camelName} = inngest.createFunction(
  {
    id: AGENT_ID,
    name: '${spec.displayName}',
    retries: ${spec.retries},
    triggers: [{ event: '${spec.triggerEvent}' }],
  },
  async ({ event, step, logger, runId }) => {
    const log = createAgentLogger({
      agent: AGENT_NAME,
      runId: runId ?? \`local-\${Date.now()}\`,
      traceId: null,
      anchors: {},
    });
    return runWithLogger(log, async () => {
      log.event('handler.start', { event_name: event.name });

      ${stepBlocks}

      ${emitBlock}

      log.event('handler.complete', {});
    });
  },
);
`;

  return {
    suggestedPath: `server/inngest/agents/${spec.slug}.ts`,
    content,
  };
}

function renderStep(step: AgentSpecStep, body: StepBody | undefined): string {
  const out = step.outputs?.[0];
  const lhs = out ? `const ${out} = ` : '';
  const bodyContent = body
    ? body.body.trim()
    : `// TODO: ${step.description}\n        // ${step.callsLib ? `(suggested lib: ${step.callsLib})` : '(no lib hint)'}\n        return null;`;
  return `${lhs}await step.run('${step.id}', async () => {
        ${bodyContent}
      });`;
}

function collectImports(
  spec: AgentSpec,
  stepBodyById: Map<string, StepBody>,
): Array<{ from: string; names: Set<string> }> {
  const map = new Map<string, Set<string>>();
  const add = (from: string, names: string[]) => {
    const set = map.get(from) ?? new Set<string>();
    for (const n of names) set.add(n);
    map.set(from, set);
  };

  // Always-needed runtime imports. NonRetriableError is part of the AO error
  // idiom (every production agent imports it for null-guards / 4xx short-circuit),
  // so emit it unconditionally rather than relying on the LLM to declare it.
  add('@/server/inngest/client', ['inngest']);
  add('@/lib/agent-logger', ['createAgentLogger', 'runWithLogger']);
  add('inngest', ['NonRetriableError']);

  // Per-step lib hints from the spec.
  for (const step of spec.steps) {
    if (step.callsLib) {
      const t = findTool(step.callsLib);
      if (t) add(t.importFrom, [t.importName]);
    }
    const body = stepBodyById.get(step.id);
    if (body?.imports) {
      for (const imp of body.imports) add(imp.from, imp.names);
    }
  }

  return Array.from(map.entries()).map(([from, names]) => ({ from, names }));
}

function formatImports(imps: Array<{ from: string; names: Set<string> }>): string {
  return imps
    .map((i) => `import { ${[...i.names].sort().join(', ')} } from '${i.from}';`)
    .sort()
    .join('\n');
}

function kebabToCamel(s: string): string {
  return s
    .split('-')
    .map((p, i) => (i === 0 ? p : p[0].toUpperCase() + p.slice(1)))
    .join('');
}
